Update the     README.md file to describe the     repo.
derachimso/my-portfolio pull request #1
Opened 2020-06-02 02:06 UTC by derachimso

Changes according to the Cloud Shell tutorial.

2020-06-13 14:13 UTC, magwitz requested changes

2020-06-13 14:13 UTC, magwitz commented on portfolio/src/main/webapp/index.html
> +
Please delete some of these extra empty lines throughout the file.

2020-06-13 14:13 UTC, magwitz commented on portfolio/src/main/webapp/index.html
> +      <h1>CONTACT ME</h1> -->
You can probably just delete this too

2020-06-13 14:13 UTC, magwitz commented on portfolio/src/main/webapp/index.html
> +                <hr /> -->
You can probably just delete this

2020-06-15 03:07 UTC, zhanche-cp approved these changes
Looks good to me other than Maggie's comments. Please apply fixes and then merge code to project. This is great progress.

2020-06-15 20:51 UTC, derachimso reviewed
Hey guys, I made and committed the changes you suggested.

2020-06-15 21:19 UTC, magwitz approved these changes

2020-06-15 21:19 UTC, magwitz commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +//     comments.add("I am a phenomenal girl");
You can probably delete these too, since it doesn't look like you're using them anyway.

2020-06-15 22:13 UTC, merged